#!/usr/bin/env python3
"""Build Startup Launcher as a single executable file.

One command; run it on the system the file is meant for, because PyInstaller
cannot build for another one:

    ./build-exe.py      Linux -> dist/startup-launcher-linux-x86_64-<version>-build<build>

Startup Launcher runs on Linux only (fcntl locks, a Unix control socket,
wmctrl/xprop, freedesktop autostart), so there is no Windows or macOS file.

What it does:

1. creates a private build environment in ``build/exe/venv`` with the system's
   PyGObject linked in, which pip cannot install - without it there is no tray
   icon,
2. installs PyInstaller (the program itself needs nothing beyond the standard
   library, tkinter and PyGObject),
3. writes the VERSION file from the history and stages it together with the
   icon and the example entries, which the executable needs as data,
4. runs PyInstaller and checks that the result starts.

Everything the program starts - the configured entries, wmctrl, xprop - stays
the system's.

Options:

    --clean     rebuild the build environment from scratch
    --keep-env  reuse the build environment without updating its packages

Author:  Joachim Ruf, Loresoft.de
"""

from __future__ import annotations

import argparse
import importlib.metadata
import importlib.util
import shutil
import subprocess
import sys
import venv
from pathlib import Path
from typing import List

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

import paths  # noqa: E402
import version  # noqa: E402

BUILD_DIR = ROOT / "build" / "exe"
VENV_DIR = BUILD_DIR / "venv"
STAGE_DIR = BUILD_DIR / "stage"
WORK_DIR = BUILD_DIR / "work"
SPEC_FILE = WORK_DIR / "startup-launcher.spec"
DIST_DIR = ROOT / "dist"

#: The same PyInstaller generation YouTube Clipster builds with.
PYINSTALLER_SPEC = "pyinstaller>=6.9"

#: The program's own packages.  Imported normally, but collected completely so
#: nothing depends on PyInstaller seeing every import.
PROGRAM_PACKAGES = ["config", "models", "services", "ui"]

#: The GTK modules the tray icon loads lazily.
GI_MODULES = ["gi.repository.Gtk", "gi.repository.Gdk", "gi.repository.GLib"]

#: The read-only data the executable needs, relative to the project root.
DATA_FILES = [
    Path("resources") / "startup-launcher.png",
    Path("entries.example.json"),
]

#: GTK's share data, limited to what a tray menu needs.  Unlimited, PyInstaller
#: packs every icon and theme of the build machine - over a gigabyte on Mint.
GTK_HOOK_CONFIG = {
    "gi": {
        "icons": [],
        "themes": [],
        "languages": ["de", "en"],
        "module-versions": {"Gtk": "3.0"},
    },
}

SPEC_TEMPLATE = '''# Generated by build-exe.py - edit that script, not this file.
from PyInstaller.utils.hooks import collect_submodules

datas = {datas!r}
binaries = []
hiddenimports = {hidden!r}
for package in {submodules!r}:
    hiddenimports += collect_submodules(package)

a = Analysis(
    [{entry!r}],
    pathex=[{root!r}],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={hooksconfig!r},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name={name!r},
    debug=False,
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    # A desktop program: started from a launcher, the tray or the login autostart.
    console=False,
    icon=None,
)
'''


def info(message: str) -> None:
    """Print a progress line."""
    print("[build-exe] " + message, flush=True)


def fail(message: str) -> None:
    """Print an error and stop with exit code 1."""
    print("[build-exe] ERROR: " + message, file=sys.stderr, flush=True)
    sys.exit(1)


def venv_python() -> Path:
    """Return the interpreter of the build environment."""
    return VENV_DIR / "bin" / "python"


def run(command: List[object], **kwargs) -> None:
    """Run a command and stop the build when it fails."""
    info("$ " + " ".join(str(part) for part in command))
    completed = subprocess.run([str(part) for part in command], **kwargs)
    if completed.returncode != 0:
        fail("command failed with exit code {0}".format(completed.returncode))


def check_build_host() -> None:
    """Stop early when this machine cannot produce a complete program."""
    if not sys.platform.startswith("linux"):
        fail("Startup Launcher runs on Linux only; build it on Linux.")
    if sys.version_info < (3, 9):
        fail("building needs Python 3.9 or newer.")
    try:
        import tkinter  # noqa: F401
    except ImportError:
        fail("tkinter is missing - sudo apt install python3-tk")
    if system_gi() is None:
        info("WARNING: PyGObject is missing - this build will have no tray icon.")
        info("         Debian/Ubuntu/Mint: sudo apt install python3-gi gir1.2-gtk-3.0")


def system_gi() -> "Path | None":
    """Return the PyGObject package of this interpreter, or ``None``."""
    spec = importlib.util.find_spec("gi")
    if spec is None or not spec.submodule_search_locations:
        return None
    return Path(list(spec.submodule_search_locations)[0])


def venv_site_packages() -> Path:
    """Return the ``site-packages`` directory of the build environment."""
    completed = subprocess.run([str(venv_python()), "-c", "import sysconfig; print(sysconfig.get_paths()['purelib'])"],
                               stdout=subprocess.PIPE, check=True)
    return Path(completed.stdout.decode().strip())


def bundled_packages() -> List[str]:
    """Return the pip packages to install into the build environment.

    Only PyInstaller: the program uses the standard library, tkinter and the
    system's PyGObject, which is linked in rather than installed.
    """
    return [PYINSTALLER_SPEC]


def prepare_venv(clean: bool, keep: bool) -> None:
    """Create or refresh the build environment.

    It is created without the system packages, so nothing the build machine
    happens to have installed (numpy, lxml, ...) ends up in the executable.
    """
    if clean and VENV_DIR.exists():
        info("Removing the old build environment ...")
        shutil.rmtree(str(VENV_DIR))
    if not venv_python().exists():
        info("Creating the build environment in {0} ...".format(VENV_DIR))
        venv.EnvBuilder(with_pip=True).create(str(VENV_DIR))
    elif keep:
        info("Reusing the build environment as it is.")
        return
    run([venv_python(), "-m", "pip", "install", "--upgrade", "--disable-pip-version-check", "pip"])
    run([venv_python(), "-m", "pip", "install", "--upgrade", "--disable-pip-version-check"]
        + bundled_packages())
    gi = system_gi()
    if gi is not None:
        # The package and its metadata: PyInstaller's hook reads the version.
        sources = [gi]
        try:
            sources.append(Path(str(importlib.metadata.distribution("pygobject")._path)))
        except (importlib.metadata.PackageNotFoundError, AttributeError):
            info("WARNING: no PyGObject metadata found - PyInstaller may reject the build.")
        site = venv_site_packages()
        for source in sources:
            link = site / source.name
            if not link.exists():
                info("Linking the system {0} into the build environment ...".format(source.name))
                link.symlink_to(source, target_is_directory=True)


def build_version() -> version.Version:
    """Write the VERSION file from the history and return what it says.

    The executable has no history to read; the file it carries is its only
    source, so it has to describe the commit that is being built.
    """
    found = version.write_file(ROOT) or version.from_file(ROOT)
    if found is None or not found.is_known:
        fail("no version: neither a git history nor a VERSION file (python3 version.py --write).")
    version.forget()
    return found


def stage_data() -> Path:
    """Copy the files the executable carries as data, in the checkout's layout.

    :return: The staging directory, unpacked as the root of ``sys._MEIPASS``.
    """
    if STAGE_DIR.exists():
        shutil.rmtree(str(STAGE_DIR))
    for relative in DATA_FILES + [Path(version.VERSION_FILE.name)]:
        source = ROOT / relative
        if not source.is_file():
            fail("{0} is missing".format(source))
        destination = STAGE_DIR / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(str(source), str(destination))
    info("Staged {0} data files.".format(len(DATA_FILES) + 1))
    return STAGE_DIR


def spec_text(staged: Path) -> str:
    """Return the PyInstaller spec file.

    :param staged: The staging directory from :func:`stage_data`.
    :return: The content of the spec file.
    """
    return SPEC_TEMPLATE.format(
        datas=[(str(staged), ".")],
        hidden=GI_MODULES,
        submodules=PROGRAM_PACKAGES,
        entry=str(ROOT / "run.py"),
        root=str(ROOT),
        hooksconfig=GTK_HOOK_CONFIG,
        name=paths.executable_name(),
    )


def smoke_test(executable: Path, expected: str) -> None:
    """Start the result once and make sure it answers."""
    info("Starting {0} --version ...".format(executable.name))
    completed = subprocess.run([str(executable), "--version"], stdout=subprocess.PIPE,
                               stderr=subprocess.STDOUT, timeout=300)
    output = completed.stdout.decode("utf-8", errors="replace").strip()
    if completed.returncode != 0:
        fail("the executable did not start (exit code {0}):\n{1}".format(completed.returncode, output))
    if output and expected not in output:
        fail("the executable reports {0!r}, expected {1}".format(output, expected))
    info("OK: " + (output or "exit code 0"))


def main() -> int:
    """Run the whole build."""
    parser = argparse.ArgumentParser(description="Build Startup Launcher as a single executable file.")
    parser.add_argument("--clean", action="store_true", help="rebuild the build environment from scratch")
    parser.add_argument("--keep-env", action="store_true",
                        help="reuse the build environment without updating its packages")
    args = parser.parse_args()

    check_build_host()
    found = build_version()
    info("Startup Launcher {0} for {1}".format(found.label, paths.executable_name()))
    prepare_venv(clean=args.clean, keep=args.keep_env)
    staged = stage_data()
    WORK_DIR.mkdir(parents=True, exist_ok=True)
    SPEC_FILE.write_text(spec_text(staged), encoding="utf-8")
    run([venv_python(), "-m", "PyInstaller", "--noconfirm", "--clean",
         "--distpath", DIST_DIR, "--workpath", WORK_DIR, SPEC_FILE], cwd=str(ROOT))

    result = DIST_DIR / paths.executable_name()
    if not result.is_file():
        fail("PyInstaller finished but {0} is missing".format(result))
    smoke_test(result, found.label)
    info("Done: {0} ({1:.1f} MB)".format(result, result.stat().st_size / 1048576))
    info("This file runs on Linux with the same or a newer glibc than this machine.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
